{
 "title": "Monitor Metrics",
 "description": "Metrics related to monitor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Monitor App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Monitors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by(__name__) (monitors_active{job=\"monitor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Monitors",
   "type": "timeseries",
   "description": "Total Monitors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count by(__name__) (monitors_total{job=\"monitor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitors by Network",
   "type": "timeseries",
   "description": "Active Monitors by Network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "group by(network) (network_monitors{job=\"monitor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Networks",
   "type": "timeseries",
   "description": "Total Networks being monitored",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count by(__name__) (networks_monitored{job=\"monitor\"})",
     "legendFormat": "Networks"
    }
   ]
  },
  {
   "title": "Total Triggers",
   "type": "timeseries",
   "description": "Triggers Configured",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count by(__name__) (triggers_total{job=\"monitor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitor Container System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "cpu_usage_percentage{job=\"monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory Usage for Monitor App",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "memory_usage_percentage{job=\"monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "disk_usage_percentage{job=\"monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}